# Generated by Django 3.2.12 on 2022-04-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_event_mazemap_poi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='photo_consent',
            new_name='LEGACY_photo_consent',
        ),
    ]
